version: '3.8'
services:
    selenium:
      image: selenium/hub
      ports:
        - 4447:4447
        - 4448:4448        
        - 4449:4449
    chrome:
      image: selenium/node-chrome-debug
      shm_size: 2gb
      depends_on:
        - selenium
      environment:
        - SE_EVENT_BUS_HOST=selenium
        - SE_EVENT_BUS_PUBLISH_PORT=4442
        - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
        - SE_NODE_OVERRIDE_MAX_SESSIONS=true
        - SE_NODE_MAX_SESSIONS=10
      ports:
        - 5901:5900